name: Test

permissions:
  checks: write
  contents: write
  pull-requests: write # only required if `comment: true` was enabled

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        working-directory: ${{github.workspace}}
      - name: format
        working-directory: ${{github.workspace}}
        run: cargo fmt --all -- --check
      - name: clippy
        working-directory: ${{github.workspace}}
        run: cargo clippy
      - name: cargo check
        working-directory: ${{github.workspace}}
        run: cargo check

  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        working-directory: ${{github.workspace}}
        run: cargo test -- -Z unstable-options --format json --report-time | bin/cargo2junit > report.xml
      - name: coverage
        working-directory: ${{github.workspace}}
        run: cargo tarpaulin --engine llvm --out xml
      - name: Test Report
        uses: mikepenz/action-junit-report@v5
        if: (success() || failure())
        with:
          report_paths: '${{github.workspace}}/report.xml'
          comment: true
          updateComment: true
          include_passed: true
          detailed_summary: true

      - name: Generate Badge
        if: (success() || failure()) && github.ref == 'refs/heads/master'
        uses: cjlapao/simple-badge-generator-action@v1
        with:
          badge-path: '${{github.workspace}}/cov-report/coverage.svg'
          badge-type: 'cobertura'
          title: 'Coverage'
          cobertura-path: '${{github.workspace}}cobertura-.xml'
          cobertura-color-yellow-threshold: 75
          cobertura-color-green-threshold: 90

      - name: GH Pages Coverage Report
        if: (success() || failure()) && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: cov-report

      - name: Generate Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          badge: true
          filename: cov-report/cobertura-coverage.xml
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: false
          output: both
          thresholds: '75 90'

      - name: Code Coverage
        if: success() || failure()
        working-directory: ${{github.workspace}}
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY